apiVersion: v1
# The type of object we want to make
kind: Pod
metadata:
  name: client-pod
  # tightly coupled with the service file, used to link this with the service file.
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000