apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
# Look at 'fundamentals.md' for explanation on accessModes
  accessModes: 
    - ReadWriteOnce
  resources:
  # kubernetes has to find or create a storage option that has 2 gigibytes of space
    requests:
      storage: 2Gi
    # storageClassName  is used to change the provisioning method for storage